### ISSUE TITLE
Moving new release features to `main`

### ISSUE THREAD

**Issue by lgrcia** [exoplanet-dev/jaxoplanet#207]
A lot of features in the `core_paper` branch (which is the version used in the paper) have to be incrementally integrated in the `main` branch. This issue keeps track of that.

- [x] multi-precision core using `mpmath` (#210)
- [ ] ~~making a CI pipeline producing an artifact to monitor the numerical precision of the `main` implementation (and speed)~~
- [ ] ~~using the multi-precision $A_1$ matrix in starry light curve~~
- [x] using the symmetry of the solution vector integrand for `n>2` in order to speed up numerical integration (at least 30% speedup) (#217)
- [x] rotation matrices using `s2fft` (for now only a single edge-case grad test remains to be solved) (#212)
- [x] order of numerical integration as keyword argument in starry light-curve (#197)
- [x] Fixing starry light curves amplitudes of multiple bodies (#195)

**Comment by lgrcia** [comment]
Update: We are trying to merge #212 and #217 but encounter issues with tests on macOs (only). We think it's related to the use of s2fft I'm currently trying to pin down the issue.

**Comment by lgrcia** [comment]
All done in #227
